# Generated by Django 5.1.3 on 2024-12-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comfort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wi_fi', 'Wi-Fi'), ('air_conditioning', 'Кондиционер'), ('tv', 'Телевизор'), ('toilet', 'Туалет'), ('reclining_seats', 'Откидывающиеся сиденья'), ('charging_ports', 'Зарядные порты')], default='Нет удобств', max_length=100, verbose_name='Удобство')),
            ],
        ),
        migrations.RemoveField(
            model_name='bus',
            name='comforts',
        ),
        migrations.AddField(
            model_name='bus',
            name='comforts',
            field=models.ManyToManyField(to='busapp.comfort', verbose_name='Удобства'),
        ),
    ]
