# Generated by Django 5.1.3 on 2024-12-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_comfort_remove_bus_comforts_bus_comforts'),
    ]

    operations = [
        migrations.AddField(
            model_name='comfort',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL Изображения'),
        ),
    ]
