# Generated by Django 5.1.3 on 2024-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0003_comfort_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comfort',
            name='image_url',
        ),
        migrations.AddField(
            model_name='comfort',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comforts/', verbose_name='Изображение'),
        ),
    ]
